---
abstract: 'Moose XML Processor'
author:
  - 'Catalyst SRS Team <team-srs@catalyst.net.nz>'
build_requires:
  Scriptalicious: 1.16
  XML::Compare: 0.04
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PRANG
no_index:
  directory:
    - doc
    - inc
    - t
requires:
  Moose: 0.92
  MooseX::Method::Signatures: 0.17
  Set::Object: 1.09
  XML::LibXML: 1.65
  perl: 5.01
version: 0.11
